default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pharma_transport_development

test:
  <<: *default
  database: pharma_transport_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] ? ENV['DATABASE_URL'].split('?').first.split('/').last : "pharma_transport_production" %>
